name: zeczec manual crawler

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "the reason that you want to re-run"
        required: false
jobs:
  crawl:
    runs-on: 'ubuntu-latest'
    container:
      image: zhang699/zeczec:latest
      credentials:
        username: zhang699
        password: ${{ secrets.DOCKER_HUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - name: "Run"
        run: "node /app/src/index.js"
        env:
          TARGET_ZECZEC_PROJECT: "https://www.zeczec.com/projects/plantpractice2021"
          SECRET_TOKEN: ${{secrets.SECRET_TOKEN}}
